name: tap_on_scroll
description: A Flutter package that ensures reliable tap events on scrollable widgets even during scroll motion. Perfect for lists, grids, and sliver widgets that need consistent touch interactions.

version: 0.0.2+1
homepage: https://github.com/00Adnan00/tap-on-scroll
repository: https://github.com/00Adnan00/tap-on-scroll.git
issue_tracker: https://github.com/00Adnan00/tap-on-scroll/issues
documentation: https://github.com/00Adnan00/tap-on-scroll#readme

# Keywords help with discoverability on pub.dev
topics:
  - scrolling
  - tap-while-scrolling
  - tappable-scroll
  - tappable
  - tap-on-scroll

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
